

PLANT_ACTION = 0
HARVEST_ACTION = 1

RULE_ACTION = 5
RAID_ACTION = 6
CONQUER_ACTION = 7
DEFEND_ACTION = 8
BUILD_ACTION = 9


action_names = {
    PLANT_ACTION: "Plant",
    HARVEST_ACTION: "Harvest",

    RULE_ACTION: "Rule",
    RAID_ACTION: "Raid",
    CONQUER_ACTION: "Conquer",
    DEFEND_ACTION: "Defend",
    BUILD_ACTION: "Build",
}

test_actions = [PLANT_ACTION, RULE_ACTION, BUILD_ACTION, CONQUER_ACTION]
